import { addons } from '@storybook/manager-api';
import { create } from '@storybook/theming/create';

const theme = create({
  base: 'light',
  brandTitle: 'Doc Forge Buddy - Component Library',
  brandUrl: 'https://github.com/your-org/doc-forge-buddy',
  brandImage: '/icon-192x192.png',
  colorPrimary: '#3b82f6',
  colorSecondary: '#8b5cf6',
  appBg: '#ffffff',
  appContentBg: '#f8fafc',
  appBorderColor: '#e2e8f0',
  appBorderRadius: 8,
  fontBase: `Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif`,
  fontCode: `Fira Code, Monaco, Menlo, Ubuntu Mono, monospace`,
  textColor: '#1e293b',
  textInverseColor: '#ffffff',
  barBg: '#ffffff',
  barTextColor: '#64748b',
  barSelectedColor: '#3b82f6',
  inputBg: '#ffffff',
  inputBorder: '#e2e8f0',
  inputBorderRadius: 6,
  inputTextColor: '#1e293b',
  buttonBg: '#3b82f6',
  buttonText: '#ffffff',
  buttonBorderRadius: 6,
  // Dark mode
  dark: {
    base: 'dark',
    brandTitle: 'Doc Forge Buddy - Component Library (Dark)',
    brandImage: '/icon-192x192.png',
    colorPrimary: '#60a5fa',
    colorSecondary: '#a78bfa',
    appBg: '#0f172a',
    appContentBg: '#1e293b',
    appBorderColor: '#334155',
    appBorderRadius: 8,
    fontBase: `Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif`,
    fontCode: `Fira Code, Monaco, Menlo, Ubuntu Mono, monospace`,
    textColor: '#f1f5f9',
    textInverseColor: '#0f172a',
    barBg: '#1e293b',
    barTextColor: '#94a3b8',
    barSelectedColor: '#60a5fa',
    inputBg: '#1e293b',
    inputBorder: '#334155',
    inputBorderRadius: 6,
    inputTextColor: '#f1f5f9',
    buttonBg: '#60a5fa',
    buttonText: '#0f172a',
    buttonBorderRadius: 6,
  }
});

addons.setConfig({
  theme: theme,
  panelPosition: 'bottom',
  showNav: true,
  showPanel: true,
  showToolbar: true,
  enableShortcuts: true,
});