/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import {
  StaleWhileRevalidate,
  CacheFirst,
  NetworkFirst,
} from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Configurações de cache
const CACHE_VERSION = 'v1.0.0';
const STATIC_CACHE = `static-${CACHE_VERSION}`;
const DYNAMIC_CACHE = `dynamic-${CACHE_VERSION}`;
const IMAGES_CACHE = `images-${CACHE_VERSION}`;
const API_CACHE = `api-${CACHE_VERSION}`;

// URLs críticas para cache offline
const CRITICAL_URLS = [
  '/',
  '/login',
  '/contratos',
  '/static/css/main.css',
  '/static/js/main.js',
];

// Set up App Shell-style routing
const fileExtensionRegexp = /\/[^/?]+\.[^/]+$/;
registerRoute(
  ({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    return true;
  },
  createHandlerBoundToURL(self.location.origin + '/index.html')
);

// Cache de imagens com estratégia Cache First (otimizado)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: IMAGES_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 dias
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache de assets estáticos (CSS, JS, fonts) com Stale While Revalidate
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style' ||
    request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: STATIC_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 dias
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache de requisições Supabase com Network First
registerRoute(
  ({ url }) =>
    url.origin.includes('supabase') ||
    (url.origin === self.location.origin && url.pathname.includes('supabase')),
  new NetworkFirst({
    cacheName: API_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 10 * 60, // 10 minutos
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache de documentos públicos com Network First
registerRoute(
  ({ url }) => url.pathname.includes('/documento-publico/'),
  new NetworkFirst({
    cacheName: DYNAMIC_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60, // 1 hora
      }),
    ],
  })
);

// Cache de páginas com Network First
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(/\/[^/?]+\.[^/]+$/)) return false;
    return true;
  },
  new NetworkFirst({
    cacheName: DYNAMIC_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 horas
      }),
    ],
  })
);

// Event listeners para gerenciamento de cache e atualizações
self.addEventListener('install', (event) => {
  // Log removido para produção (Lighthouse)
  event.waitUntil(
    caches
      .open(STATIC_CACHE)
      .then((cache) => {
        // Log removido para produção (Lighthouse)
        return cache.addAll(CRITICAL_URLS);
      })
      .then(() => {
        // Log removido para produção (Lighthouse)
        return self.skipWaiting();
      })
  );
});

self.addEventListener('activate', (event) => {
  // Log removido para produção (Lighthouse)
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            if (
              ![STATIC_CACHE, DYNAMIC_CACHE, IMAGES_CACHE, API_CACHE].includes(
                cacheName
              )
            ) {
              // Log removido para produção (Lighthouse)
              return caches.delete(cacheName);
            }
          })
        );
      })
      .then(() => {
        // Log removido para produção (Lighthouse)
        return self.clients.claim();
      })
  );
});

// Mensagens do cliente
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  if (event.data && event.data.type === 'GET_CACHE_STATUS') {
    event.ports[0].postMessage({
      type: 'CACHE_STATUS',
      cacheNames: [STATIC_CACHE, DYNAMIC_CACHE, IMAGES_CACHE, API_CACHE],
    });
  }

  if (event.data && event.data.type === 'CLEAR_CACHE') {
    event.waitUntil(
      caches
        .keys()
        .then((cacheNames) => {
          return Promise.all(
            cacheNames.map((cacheName) => caches.delete(cacheName))
          );
        })
        .then(() => {
          event.ports[0].postMessage({ type: 'CACHE_CLEARED' });
        })
    );
  }
});

// Background sync para funcionalidades offline
self.addEventListener('sync', (event) => {
  if (event.tag === 'background-sync') {
    // Log removido para produção (Lighthouse)
    event.waitUntil(doBackgroundSync());
  }
});

async function doBackgroundSync() {
  try {
    // Implementar lógica de sincronização offline
    // Log removido para produção (Lighthouse)
  } catch {
    // Log removido para produção (Lighthouse)
  }
}

// Push notifications (preparado para futuras implementações)
self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json();
    const options = {
      body: data.body,
      icon: '/icon-192x192.png',
      badge: '/icon-72x72.png',
      vibrate: [100, 50, 100],
      data: {
        dateOfArrival: Date.now(),
        primaryKey: data.primaryKey,
      },
      actions: [
        {
          action: 'explore',
          title: 'Ver detalhes',
          icon: '/icon-72x72.png',
        },
        {
          action: 'close',
          title: 'Fechar',
          icon: '/icon-72x72.png',
        },
      ],
    };

    event.waitUntil(self.registration.showNotification(data.title, options));
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'explore') {
    event.waitUntil(clients.openWindow('/'));
  }
});
