export type Json =
  | string
  | number
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // This file is automatically generated. Do not edit it directly.
  // Last updated: 2025-10-05T12:45:00
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '13.0.4';
  };
  public: {
    Tables: {
      chat_images: {
        Row: {
          created_at: string | null;
          file_name: string | null;
          file_size: number | null;
          file_type: string | null;
          id: string;
          image_data: string | null;
          image_url: string;
          message_id: string | null;
        };
        Insert: {
          created_at?: string | null;
          file_name?: string | null;
          file_size?: number | null;
          file_type?: string | null;
          id?: string;
          image_data?: string | null;
          image_url: string;
          message_id?: string | null;
        };
        Update: {
          created_at?: string | null;
          file_name?: string | null;
          file_size?: number | null;
          file_type?: string | null;
          id?: string;
          image_data?: string | null;
          image_url?: string;
          message_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'chat_images_message_id_fkey';
            columns: ['message_id'];
            isOneToOne: false;
            referencedRelation: 'chat_messages';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          full_name: string | null;
          role: 'admin' | 'user';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email: string;
          full_name?: string | null;
          role?: 'admin' | 'user';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          full_name?: string | null;
          role?: 'admin' | 'user';
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chat_messages: {
        Row: {
          content: string;
          created_at: string | null;
          id: string;
          metadata: Json | null;
          role: string;
          session_id: string | null;
        };
        Insert: {
          content: string;
          created_at?: string | null;
          id?: string;
          metadata?: Json | null;
          role: string;
          session_id?: string | null;
        };
        Update: {
          content?: string;
          created_at?: string | null;
          id?: string;
          metadata?: Json | null;
          role?: string;
          session_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'chat_messages_session_id_fkey';
            columns: ['session_id'];
            isOneToOne: false;
            referencedRelation: 'chat_sessions';
            referencedColumns: ['id'];
          },
        ];
      };
      chat_sessions: {
        Row: {
          created_at: string | null;
          id: string;
          metadata: Json | null;
          mode: string;
          title: string;
          updated_at: string | null;
          user_id: string | null;
        };
        Insert: {
          created_at?: string | null;
          id?: string;
          metadata?: Json | null;
          mode?: string;
          title?: string;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Update: {
          created_at?: string | null;
          id?: string;
          metadata?: Json | null;
          mode?: string;
          title?: string;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      contracts: {
        Row: {
          created_at: string;
          data_comunicacao: string;
          data_inicio_desocupacao: string;
          data_termino_desocupacao: string;
          email_proprietario: string;
          endereco_imovel: string;
          id: string;
          nome_locatario: string;
          nome_proprietario: string;
          numero_contrato: string;
          prazo_dias: string;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          created_at?: string;
          data_comunicacao: string;
          data_inicio_desocupacao: string;
          data_termino_desocupacao: string;
          email_proprietario: string;
          endereco_imovel: string;
          id?: string;
          nome_locatario: string;
          nome_proprietario: string;
          numero_contrato: string;
          prazo_dias: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          created_at?: string;
          data_comunicacao?: string;
          data_inicio_desocupacao?: string;
          data_termino_desocupacao?: string;
          email_proprietario?: string;
          endereco_imovel?: string;
          id?: string;
          nome_locatario?: string;
          nome_proprietario?: string;
          numero_contrato?: string;
          prazo_dias?: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      prestadores: {
        Row: {
          cnpj: string | null;
          created_at: string | null;
          email: string | null;
          endereco: string | null;
          especialidade: string | null;
          id: string;
          nome: string;
          observacoes: string | null;
          telefone: string | null;
          updated_at: string | null;
          user_id: string | null;
        };
        Insert: {
          cnpj?: string | null;
          created_at?: string | null;
          email?: string | null;
          endereco?: string | null;
          especialidade?: string | null;
          id?: string;
          nome: string;
          observacoes?: string | null;
          telefone?: string | null;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Update: {
          cnpj?: string | null;
          created_at?: string | null;
          email?: string | null;
          endereco?: string | null;
          especialidade?: string | null;
          id?: string;
          nome?: string;
          observacoes?: string | null;
          telefone?: string | null;
          updated_at?: string | null;
          user_id?: string | null;
        };
        Relationships: [];
      };
      saved_terms: {
        Row: {
          content: string;
          created_at: string;
          document_type: string;
          form_data: Json;
          id: string;
          title: string;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          content: string;
          created_at?: string;
          document_type: string;
          form_data: Json;
          id?: string;
          title: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          content?: string;
          created_at?: string;
          document_type?: string;
          form_data?: Json;
          id?: string;
          title?: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      vistoria_analises: {
        Row: {
          apontamentos: Json;
          contract_id: string | null;
          created_at: string;
          dados_vistoria: Json;
          id: string;
          title: string;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          apontamentos?: Json;
          contract_id?: string | null;
          created_at?: string;
          dados_vistoria?: Json;
          id?: string;
          title: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          apontamentos?: Json;
          contract_id?: string | null;
          created_at?: string;
          dados_vistoria?: Json;
          id?: string;
          title?: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'vistoria_analises_contract_id_fkey';
            columns: ['contract_id'];
            isOneToOne: false;
            referencedRelation: 'saved_terms';
            referencedColumns: ['id'];
          },
        ];
      };
      vistoria_images: {
        Row: {
          apontamento_id: string;
          created_at: string;
          file_name: string;
          file_size: number;
          file_type: string;
          id: string;
          image_url: string;
          tipo_vistoria: string;
          user_id: string | null;
          vistoria_id: string | null;
        };
        Insert: {
          apontamento_id: string;
          created_at?: string;
          file_name: string;
          file_size: number;
          file_type: string;
          id?: string;
          image_url: string;
          tipo_vistoria: string;
          user_id?: string | null;
          vistoria_id?: string | null;
        };
        Update: {
          apontamento_id?: string;
          created_at?: string;
          file_name?: string;
          file_size?: number;
          file_type?: string;
          id?: string;
          image_url?: string;
          tipo_vistoria?: string;
          user_id?: string | null;
          vistoria_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'vistoria_images_vistoria_id_fkey';
            columns: ['vistoria_id'];
            isOneToOne: false;
            referencedRelation: 'vistoria_analises';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  'public'
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
